name: Test
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-15-intel, macos-14, macos-15, macos-26, ubuntu-24.04-arm, ubuntu-22.04-arm, windows-2022, windows-2025, ubuntu-24.04, ubuntu-22.04]
        nv: [21, 22, 23, 24]
      fail-fast: false
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.nv }}
    - run: rustup default stable
    - run: cargo install --git https://github.com/vedantmgoyal9/nodejs-sea-creator.git
    - run: nodejs-sea-creator -t win-x64
    - run: nodejs-sea-creator -t win-arm64
    - run: nodejs-sea-creator -t linux-arm64
    - run: nodejs-sea-creator -t linux-x64
    - run: nodejs-sea-creator -t darwin-arm64
    - run: nodejs-sea-creator -t darwin-x64
    - run: ls nodejs-sea-creator
      shell: pwsh
    - uses: softprops/action-gh-release@v2.3.3
      with:
        tag_name: nightly
        files: nodejs-sea-creator/sea-test*
        make_latest: true
        token: ${{ secrets.GITHUB_TOKEN }}

